title: NextUniverse
description: NextUniverse is bringing choice to your Minecraft experience. Pick the minigame you want, and a majority is reached watch as the server is transformed!
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
